langauge: cpp
compiler: gcc
sudo: required
dist: trusty

install:
    - sudo apt-get update

script:
  - cd ./tests && make

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
