langauge: cpp
compiler: gcc
sudo: required
dist: trusty

install:
    - sudo apt-get update

script:
  - cd ./tests && make
  - ./cov_check

after_success:
  - CODECOV_TOKEN=74a785c0-755a-4c6b-8301-141d0ca34f21
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
